### ISSUE TITLE
Suggestion - Remove .patch need

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/mod-ah-bot#1]
For full modularity, the .patch should be ditched in favor of a complete self contained module. Not sure if possible with this module

**Comment by dunjeon** [comment]
This mod does need some love... like a distant cousin, it has... issues =)

The patch file mostly works. 4 hunks are rejected. 2 of them are unnecessary (CMakeLists.txt) and can be removed or ignored.  The other two in world.cpp are required. One of them (below) is required to read the conf file, but it is in direct conflict with the code used for eluna -- Does eluna require special circumstance in the core (why can't both of these be assigned in the module(s) proper)?

#ifdef MOD_AH_BOT
    std::string conf_path = _CONF_DIR;
    std::string cfg_file = conf_path + "/mod_ahbot.conf";
#ifdef WIN32
    cfg_file = "mod_ahbot.conf";
#endif
    std::string cfg_def_file = cfg_file2 + ".dist";
    sConfigMgr->LoadMore(cfg_def_file.c_str());
    sConfigMgr->LoadMore(cfg_file.c_str());
#endif

Anyway, I'm working on removing the need for the patch file, but I'm unfamiliar with these two modules (eluna and ahbot) so more research is required.
