### ISSUE TITLE
Bug: New Update broken

### ISSUE THREAD

**Issue by Raz0r1337** [azerothcore/mod-ah-bot#100]
### Current Behaviour

Until i compile the new code (commit cb89a9d) it gives an Error.

2507 |         if (itr->second.Bonding == BIND_WHEN_EQUIPPED && !Bind_When_Equipped)

### Steps to reproduce the problem

Simple clone the actual code (commit cb89a9d) and compile it.

### Extra Notes

There is an P to much in BIND_WHEN_EQUIPPED
If i set this to BIND_WHEN_EQUIPED it compiles correctly.
Or set the Variable Name in the declaration with the extra P.
I think this is the way it should be done.

### AC rev. hash/commit

AzerothCore rev. 27b243e7b2aa 2024-08-18 23:02:22 +0800 (Playerbot branch) (Unix, RelWithDebInfo, Static)

### Operating system

Ubunto 22.04

### Custom changes or Modules

mod-playerbot
mod-anticheat
mod-ah-bot
mod-autobalance
mod-groupquests
mod-solo-lfg
mod-weekendbonus
BreakingNewsOverride

**Comment by kewinrausch** [comment]
I suppose you just have to update your core.
See [this](https://github.com/azerothcore/azerothcore-wotlk/commit/f88812443d8e2f0057416e70d8e4c474e3ca79cb) commit  for more info.

**Comment by Raz0r1337** [comment]
Oh I understand.
This issue ist because i use the module mod-playerbot. It needs a custom version of the core with some code changes to work. This Fork from liyunfan1223 is a week behind the original.

Thank you. And sorry.
