### ISSUE TITLE
Bug: Compile Error, spelling?

### ISSUE THREAD

**Issue by lanarchy** [azerothcore/mod-ah-bot#101]
### Current Behaviour

Error on running cmake

```
/root/acore/modules/mod-ah-bot/src/AuctionHouseBotConfig.cpp:2507:36: fatal error: use of undeclared identifier 'BIND_WHEN_EQUIPPED'; did you mean 'BIND_WHEN_EQUIPED'?
        if (itr->second.Bonding == BIND_WHEN_EQUIPPED && !Bind_When_Equipped)
                                   ^~~~~~~~~~~~~~~~~~
                                   BIND_WHEN_EQUIPED
/root/acore/src/server/game/Entities/Item/ItemTemplate.h:97:5: note: 'BIND_WHEN_EQUIPED' declared here
    BIND_WHEN_EQUIPED                 = 2,

```
Build continues, unknown affect when worldserver launched yet

### Expected Behaviour

No error

### Steps to reproduce the problem

```
./acore.sh module-install mod-ah-bot
cd build
cmake ../ -DCMAKE_INSTALL_PREFIX=/root/azeroth-server -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DWITH_WARNINGS=1 -DTOOLS_BUILD=all -DSCRIPTS=static -DMODULES=static

```

### AC rev. hash/commit

AzerothCore-wotlk-with-NPCBots ee76ff6

### Operating system

Linux

### Custom changes or Modules

weekend-xp, ah-bot, transmog, eluna, breaking-news-override, compiling from AzerothCore-wotlk-with-NPCBots fork

**Comment by CasperHCH** [comment]
/root/azerothcore-wotlk/modules/mod-ah-bot/src/AuctionHouseBotConfig.cpp:2507:36: fatal error: use of undeclared identifier 'BIND_WHEN_EQUIPPED'; did you mean 'BIND_WHEN_EQUIPED'?
        if (itr->second.Bonding == BIND_WHEN_EQUIPPED && !Bind_When_Equipped)
                                   ^~~~~~~~~~~~~~~~~~
                                   BIND_WHEN_EQUIPED
/root/azerothcore-wotlk/src/server/game/Entities/Item/ItemTemplate.h:97:5: note: 'BIND_WHEN_EQUIPED' declared here
    BIND_WHEN_EQUIPED                 = 2,
    ^
1 error generated.

mods: 
![image](https://github.com/user-attachments/assets/85536cf9-17ae-4b42-94cc-a03da29eae06)

**Comment by kewinrausch** [comment]
I suppose you just have to update your core.
See [this](https://github.com/azerothcore/azerothcore-wotlk/commit/f88812443d8e2f0057416e70d8e4c474e3ca79cb) commit for more info.

**Comment by lanarchy** [comment]
> I suppose you just have to update your core. See [this](https://github.com/azerothcore/azerothcore-wotlk/commit/f88812443d8e2f0057416e70d8e4c474e3ca79cb) commit for more info.

That makes sense, thanks!

**Comment by CasperHCH** [comment]
i did just update my  game - guess it havent been updated in the playerbots version

**Comment by Rockhopper1776** [comment]
> i did just update my game - guess it havent been updated in the playerbots version https://github.com/liyunfan1223/azerothcore-wotlk.git --branch=Playerbot

I use liyunfan's playerbot branch as well. Recompiled today (Sept 6) and the error is gone now.

**Comment by lanarchy** [comment]
Issue resolved. I just caught everything mid update. PEBKAC
