### ISSUE TITLE
Feature: How to Get Bot to Appear

### ISSUE THREAD

**Issue by coler-j** [azerothcore/mod-ah-bot#108]
### Describe your feature request or suggestion in detail

I am unclear how to get the bot to appear. I create an account and player , but how do i get them to appear?

**Comment by kewinrausch** [comment]
I'm sorry i did not understand you question.
What do you mean by appear?

**Comment by coler-j** [comment]
1, I have the mod installed
2 .The SQL is applied
3. I created an account for the bot and then created a user so that a guid would be generated
4. I configured the conf file to use the account and character guid from #3 above
5. I enabled `AuctionHouseBot.EnableBuyer = 1` and `AuctionHouseBot.EnableSeller = 1`
6. I ensure config is reloaded.
7. I go into auction house as my main character and there are no items listed....

How do I figure out what is going wrong?

**Comment by coler-j** [comment]
NVM I think I just didn't know how to use it
