### ISSUE TITLE
Nothing works

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/mod-ah-bot#12]
Check the comments here: https://github.com/azerothcore/mod-ah-bot/pull/11

Commands work but I see 0 item in the auction house

**Comment by SilentCLD** [comment]
This is caused by PR #11 removing the module initialization call from the patch. (as seen here: https://github.com/azerothcore/mod-ah-bot/pull/11/files#diff-85082bf585f37675ea1d901fd64176feL130)

A quick test shows that readding those 4 lines to World.cpp under the ELUNA init call (where it was originally) fixes the issue
(https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/World/World.cpp#L1983)

**Comment by BarbzYHOOL** [comment]
wait so I removed it and forgot to move it? damnit

(and the other guy who told me "I fixed the patch myself and it didn't work either" that was kinda unlucky that we both made a mistake)

thank you, gonna test and fix it

**Comment by BarbzYHOOL** [comment]
in top of that i clearly remember that part of the code and thought to myself "i need to move this below"

Alright it seems to work now, thank you, fixed in 6198ee2f30747b7dd66a517f8dd1537ed31272e1

If you use AC, do not hesitate to join our discord!

Note: it displayed items, then the second time I opened it, it loaded items forever `Searching for items...` so I'm not sure if it's working fine. After a logout it worked again. Then after waiting 30 min, it didn't work again... it's like the sql query takes forever. But i think it's because I was using the account that is used by the ahbot

**Comment by SilentCLD** [comment]
@BarbzYHOOL 
No problem.
> If you use AC, do not hesitate to join our discord!

Already am, currently just a lurker :D 

Hm, i haven't come across that issue, the auctions started appearing straight away for me. That could be a problem with the throughput of your db if you're running from a HDD and not an SSD (not sure) but I think that's more of a problem related to the core, not the module itself. I am using a separate account purely for the bot.

**Comment by BarbzYHOOL** [comment]
using a HDD and yes, i guess it's not wise to use the character used by the ahbot to browse the ahbot, even if I don't know the reason
