### ISSUE TITLE
Cannot compile on latest version AzerothCore

### ISSUE THREAD

**Issue by Krejza9** [azerothcore/mod-ah-bot#34]
mod-ah-bot cannot be compiled on latest version of AzerothCore
![image](https://user-images.githubusercontent.com/5585555/116227756-c4749c00-a754-11eb-97ac-0314facb5f63.png)

OS: Ubuntu 20.04
AzerotCore version: cabe1163d83d5958ceb6ef31302b57f7d29940a4

**Comment by Helias** [comment]
I guess it's related with the ObjectGuid PR.

Sorry @ultranix to bother you but we need to make all the possible modules compatible :sweat:.

If anyone has time, we need to change uint64 guids with the ObjectGuid class to make it compatible

**Comment by UltraNix** [comment]
@Helias No problem - my fault I overlooked these.
