### ISSUE TITLE
Errors compiling

### ISSUE THREAD

**Issue by benjymansy123** [azerothcore/mod-ah-bot#39]
> /usr/bin/ld: ../scripts/libscripts.a(ScriptLoader.cpp.o): in function `AddScripts()':
> ScriptLoader.cpp:(.text+0x49): undefined reference to `Addmod_ah_bot_masterScripts()'
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make[2]: *** [src/server/worldserver/CMakeFiles/worldserver.dir/build.make:174: src/server/worldserver/worldserver] Error 1
> make[1]: *** [CMakeFiles/Makefile2:1285: src/server/worldserver/CMakeFiles/worldserver.dir/all] Error 2
> make: *** [Makefile:130: all] Error 2

Only occurs with the ah-bot module installed.

**Comment by jagehring** [comment]
remove master from folder and recompile.

**Comment by Winfidonarleyan** [comment]
use `git clone` please
