### ISSUE TITLE
Unable to compile after the API update

### ISSUE THREAD

**Issue by tkn963** [azerothcore/mod-ah-bot#42]
I can't compile the module after the update to the new API.
This has been a problem for a while now so I can't imagine I would be required to say anything other than I'm always using the latest possible commit of both the core and the module.

I haven't changed my setup at all since before this started happening, so I can't find a way of fixing it except modifying the code myself before compiling it.

**Error message**
```
/usr/bin/ld: ../scripts/libscripts.a(ScriptLoader.cpp.o): in function `AddScripts()':
/opt/azerothcore/build/src/server/scripts/gen_scriptloader/static/ScriptLoader.cpp:71: undefined reference to `AddahbotScripts()'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/server/worldserver/CMakeFiles/worldserver.dir/build.make:194: src/server/worldserver/worldserver] Error 1
make[1]: *** [CMakeFiles/Makefile2:1249: src/server/worldserver/CMakeFiles/worldserver.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```

**Comment by Winfidonarleyan** [comment]
https://github.com/azerothcore/mod-ah-bot/runs/3156046550

**Comment by Winfidonarleyan** [comment]
Clean build and run compile

**Comment by tkn963** [comment]
> 
> 
> Clean build and run compile

I tried deleting and cloning both AC and the module but the issue still happens. I'm confused because this is the only module I have this issue with.

These are the exact steps I take.

```
git clone --recursive --branch master https://github.com/azerothcore/azerothcore-wotlk.git /opt/azerothcore
git clone --recursive --branch master https://github.com/azerothcore/mod-ah-bot.git /opt/azerothcore/modules/ahbot
mkdir -p /opt/azerothcore/build && cd $_
cmake ../ -DCMAKE_INSTALL_PREFIX=/opt/azerothcore -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DWITH_WARNINGS=0 -DTOOLS=0 -DSCRIPTS=static
make -j $(nproc)
make install
```

And this is **always** the result.

```
[100%] Linking CXX executable worldserver
/usr/bin/ld: ../scripts/libscripts.a(ScriptLoader.cpp.o): in function `AddScripts()':
/opt/azerothcore/build/src/server/scripts/gen_scriptloader/static/ScriptLoader.cpp:71: undefined reference to `AddahbotScripts()'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/server/worldserver/CMakeFiles/worldserver.dir/build.make:193: src/server/worldserver/worldserver] Error 1
make[1]: *** [CMakeFiles/Makefile2:1178: src/server/worldserver/CMakeFiles/worldserver.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```

**Comment by tkn963** [comment]
I think I've found the issue.

I removed
```
-DSCRIPTS=static
```

From CMake and it compiled. I also cloned it into /modules/mod-ah-bot instead of /modules/ahbot but if that made a difference it would be absurd.

**Comment by Winfidonarleyan** [comment]
> I removed
> ```
> DSCRIPTS=static
> ```

This default option

**Comment by Winfidonarleyan** [comment]
> From CMake and it compiled. I also cloned it into /modules/mod-ah-bot instead of /modules/ahbot but if that made a difference it would be absurd.

Yes, it does matter.
