### ISSUE TITLE
Wont build 

### ISSUE THREAD

**Issue by godlike73** [azerothcore/mod-ah-bot#61]
Get this error when building
azerothcore-wotlk/modules/azerothcore_mod_AHbot/src/AuctionHouseBot.cpp:126:30: fatal error: no member named 'outString' in 'Log'
        if (debug_Out) sLog->outString("AHSeller: Disabled");

**Comment by maluramichael** [comment]
What system and compiler did you use?

**Comment by godlike73** [comment]
Umm i dont remember now it was a bit back there was a few commits since then and it built great since
