### ISSUE TITLE
ItemPrototype.h missing?

### ISSUE THREAD

**Issue by lmortal** [azerothcore/mod-ah-bot#7]
1>------ Build started: Project: revision.h, Configuration: Debug x64 ------
2>------ Skipped Build: Project: clean_cotire, Configuration: Debug x64 ------
2>Project not selected to build for this solution configuration 
3>------ Build started: Project: game, Configuration: Debug x64 ------
4>------ Build started: Project: scripts, Configuration: Debug x64 ------
3>AuctionHouseMgr.cpp
3>Mail.cpp
3>World.cpp
3>I:\Azerothcore1\azerothcore\modules\mod-ah-bot-master\src\AuctionHouseBot.h(29): fatal error C1083: Cannot open include file: 'ItemPrototype.h': No such file or directory (compiling source file I:\Azerothcore1\azerothcore\src\server\game\Mails\Mail.cpp)
3>I:\Azerothcore1\azerothcore\modules\mod-ah-bot-master\src\AuctionHouseBot.h(29): fatal error C1083: Cannot open include file: 'ItemPrototype.h': No such file or directory (compiling source file I:\Azerothcore1\azerothcore\src\server\game\AuctionHouse\AuctionHouseMgr.cpp)
4>cs_ah_bot.cpp
4>AuctionHouseBot.cpp
4>i:\azerothcore1\azerothcore\modules\mod-ah-bot-master\src\AuctionHouseBot.h(29): fatal error C1083: Cannot open include file: 'ItemPrototype.h': No such file or directory (compiling source file I:\Azerothcore1\azerothcore\modules\mod-ah-bot-master\src\cs_ah_bot.cpp)
4>i:\azerothcore1\azerothcore\modules\mod-ah-bot-master\src\AuctionHouseBot.h(29): fatal error C1083: Cannot open include file: 'ItemPrototype.h': No such file or directory (compiling source file I:\Azerothcore1\azerothcore\modules\mod-ah-bot-master\src\AuctionHouseBot.cpp)
3>I:\Azerothcore1\azerothcore\modules\mod-ah-bot-master\src\AuctionHouseBot.h(29): fatal error C1083: Cannot open include file: 'ItemPrototype.h': No such file or directory (compiling source file I:\Azerothcore1\azerothcore\src\server\game\World\World.cpp)
4>Done building project "scripts.vcxproj" -- FAILED.
3>Done building project "game.vcxproj" -- FAILED.
5>------ Build started: Project: worldserver, Configuration: Debug x64 ------
5>LINK : fatal error LNK1104: cannot open file '..\game\Debug\game.lib'
5>Done building project "worldserver.vcxproj" -- FAILED.
6>------ Skipped Build: Project: INSTALL, Configuration: Debug x64 ------
6>Project not selected to build for this solution configuration 
========== Build: 1 succeeded, 3 failed, 11 up-to-date, 2 skipped ==========

**Comment by Viste** [comment]
see last commits on master file renamed

**Comment by Viste** [comment]
omg...
