### ISSUE TITLE
core path

### ISSUE THREAD

**Issue by Mitradis** [azerothcore/mod-ah-bot#8]
Core path have problem with last AC build.  World.cpp was changed in last commits.
https://media.discordapp.net/attachments/284406375495368704/631442616374001711/unknown.png?width=1008&height=630

**Comment by pagimu** [comment]
same issue here. Is there any news? Thank you

**Comment by BarbzYHOOL** [comment]
that's the problem with patches, you need to try to apply it manually line by line, and then you should make a "git patch" and post it here
