### ISSUE TITLE
Bug: [PARTIAL FIX INCLUDED] Deprecated Items in Default Settings

### ISSUE THREAD

**Issue by StraysFromPath** [azerothcore/mod-ah-bot#80]
### Current Behaviour

![image](https://github.com/azerothcore/mod-ah-bot/assets/119371540/6545d69f-9e16-4ef0-877e-b513f1373587)

### Expected Behaviour

No deprecated/deleted/QA test items should be present in the AH bot.

### Steps to reproduce the problem

Install AHbot

Use default settings

Observe deprecated items

### Extra Notes

FIX:

This only removes the deprecated items that generated into my default/first gen of the AH. There's a good chance there's hundreds of other deprecated items to remove.

INSERT INTO `mod_auctionhousebot_disabled_items` (`item`) VALUES (1963);
INSERT INTO `mod_auctionhousebot_disabled_items` (`item`) VALUES (2322);
INSERT INTO `mod_auctionhousebot_disabled_items` (`item`) VALUES (1950);
INSERT INTO `mod_auctionhousebot_disabled_items` (`item`) VALUES (1695);
INSERT INTO `mod_auctionhousebot_disabled_items` (`item`) VALUES (1689);
INSERT INTO `mod_auctionhousebot_disabled_items` (`item`) VALUES (786);
INSERT INTO `mod_auctionhousebot_disabled_items` (`item`) VALUES (1654);
INSERT INTO `mod_auctionhousebot_disabled_items` (`item`) VALUES (784);

### AC rev. hash/commit

n/a

### Operating system

win10

**Comment by BarbzYHOOL** [comment]
Can you make a small PR for it?

**Comment by StraysFromPath** [comment]
INSERT INTO `mod_auctionhousebot_disabled_items`
VALUES 
(1693),
(2323),
(808),
(1638),
(807),
(741),
(23418),
(2678),
(3371),
(4289),
(2320),
(44835),
(39354),
(39505),
(10648),
(39501),
(3372),
(8925),
(18256);


More shit to remove.

**Comment by StraysFromPath** [comment]
There's also 500+ seasonal items like snowballs, thanksgiving spices, etc which are pointless and also should not be in this.

**Comment by StraysFromPath** [comment]
REPLACE INTO `mod_auctionhousebot_disabled_items`
VALUES 
(1695),
(786),
(1654),
(784),
(1963),
(2322),
(1950);

More stuff to disable.

**Comment by Helias** [comment]
Thanks for the informations, please [open a PR](https://www.azerothcore.org/wiki/how-to-create-a-pr) with the fix
