### ISSUE TITLE
cant compile worldserver 

### ISSUE THREAD

**Issue by blade10101** [azerothcore/mod-ah-bot#82]
### Current Behaviour

compile crashes

### Expected Behaviour

It should compile

### Steps to reproduce the problem

downloaded the ahbot to the module directory.
I starter a recompile of the worldserver

### Extra Notes

on `AddModulesScripts()':
46.97 ModulesLoader.cpp:(.text+0x1): undefined reference to `Addmod_ah_bot_masterScripts()'
47.28 clang: error: linker command failed with exit code 1 (use -v to see invocation)
47.28 gmake[2]: *** [src/server/apps/CMakeFiles/worldserver.dir/build.make:192: src/server/apps/worldserver] Error 1
47.28 gmake[1]: *** [CMakeFiles/Makefile2:1020: src/server/apps/CMakeFiles/worldserver.dir/all] Error 2
47.28 gmake: *** [Makefile:136: all] Error 2
------
failed to solve: process "/bin/sh -c git config --global --add safe.directory /azerothcore     && cmake /azerothcore        -DCMAKE_INSTALL_PREFIX=\"/azerothcore/env/dist\"         -DAPPS_BUILD=\"all\"                                     -DTOOLS_BUILD=\"$CTOOLS_BUILD\"                          -DSCRIPTS=\"$CSCRIPTS\"                                  -DMODULES=\"$CMODULES\"                                  -DWITH_WARNINGS=\"$CWITH_WARNINGS\"                      -DCMAKE_BUILD_TYPE=\"$CTYPE\"                            -DCMAKE_CXX_COMPILER=\"clang++\"                         -DCMAKE_C_COMPILER=\"clang\"                             -DCMAKE_CXX_COMPILER_LAUNCHER=\"ccache\"                 -DCMAKE_C_COMPILER_LAUNCHER=\"ccache\"                   -DBoost_USE_STATIC_LIBS=\"ON\"                        && cmake --build . --config \"$CTYPE\" -j $(($(nproc) + 1))     && cmake --install . --config \"$CTYPE\"" did not complete successfully: exit code: 2

### AC rev. hash/commit

none

### Operating system

ubuntu 22.04 and docker

**Comment by DrZack-CN** [comment]
`on AddModulesScripts()': 46.97 ModulesLoader.cpp:(.text+0x1): undefined reference to Addmod_ah_bot_masterScripts()'`

Is it possible that the folder's name you put in the modules folder has '-master' in the end?
Try to remove the '-master' if that's the case.
