### ISSUE TITLE
Feature: Autoinstall of sql

### ISSUE THREAD

**Issue by morgannilsson** [azerothcore/mod-ah-bot#87]
### Describe your feature request or suggestion in detail

If the sql file was to be moved from:

/azerothcore-wotlk/modules/mod-ah-bot/data/sql/db-world/base 
to
/azerothcore-wotlk/modules/mod-ah-bot/sql/world
It would install automatically.

### Additional context

Log:
Applying update "mod_auctionhousebot.sql" 'EB89E9B'...

**Comment by Helias** [comment]
hi, thanks, you could move the sql file and [make a PR](https://www.azerothcore.org/wiki/how-to-create-a-pr)

**Comment by Helias** [comment]
it has been done from another user, thanks for the issue
