### ISSUE TITLE
Feature: Mor chars used from the AH-Bot

### ISSUE THREAD

**Issue by Raz0r1337** [azerothcore/mod-ah-bot#90]
### Describe your feature request or suggestion in detail

Hi, i look for a feature to get the AH-Bot use more than one Character at my AHBot Account at once like the AH-Bot on TrinityCore.

This would make the server looks more like an populated server and will be very good for immersion.

### Describe a possible solution to your feature or suggestion in detail

TrinityCore has an AH-Bot who works exactly like i was writing above.

**Comment by kewinrausch** [comment]
This is now possible to do by using the last version of the mod.
If you don't specify the character GUID but keep a valid account id in the configuration, the bot is instructed to use all the characters of that account for auctioning.

**Comment by Helias** [comment]
thanks @kewinrausch for the explanation, I am closing the issue.

**Comment by Raz0r1337** [comment]
Thank you very much.
